name: UAP Detector V1

on:
  schedule:
    # Uruchamia skrypt automatycznie co 15 minut
    - cron: '*/15 * * * *'
  workflow_dispatch:
    # Pozwala na ręczne uruchomienie przyciskiem w zakładce Actions

jobs:
  run-detector:
    runs-on: ubuntu-latest

    steps:
      - name: Pobieranie kodu repozytorium
        uses: actions/checkout@v4

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Uruchomienie detektora UAP
        run: python app.py
